### ISSUE TITLE
USER STORY: User Login and Logout

### ISSUE THREAD

**Issue by Quack842** [Quack842/p4-dndcampaign#3]
As a **Site User**, I can log in or log out of my account so that I can view my **booking history** as well as all my **campaigns**.

**Acceptance Criteria logged-out user**
1. Sign in button should be visible on the home page, on the navbar.
2. When I click the button I should be taken to the log-in page.
3. When I fill in my details and click submit I should be logged in.
4. I should then be notified that I have been logged in successfully.
5. If I enter the incorrect credentials I should receive feedback on what information was incorrectly entered.

**Acceptance Criteria logged in user**
1. When I click the log out button I should be asked to confirm I want to log out.
2. When I confirm I wish to log out I should be notified that I have been logged out successfully.

**Tasks**
- [ ] Install allauth and add to installed apps
- [ ] Add allauth urls
- [ ] Add log in and log out links to navbar
- [ ] Customise allauth login, logout HTML templates
- [ ] Create success messages for successful login/logout
