### ISSUE TITLE
USER STORY: Venues - Interactive Map

### ISSUE THREAD

**Issue by Quack842** [Quack842/p4-dndcampaign#7]
As a **Site User** I can **interact with the map** to select the **region where I want to book** a venue for my campaign.

**Acceptance Criteria**
1. When the user hovers over the different regions, it will highlight/grow slightly.
2. When the user clicks on a region, it will show the available veneus in said region.
3. When all the available venues are shown, the user will be able to click and book a spot in said venue.

**Task**
- [ ] Create an onhover effect.
- [ ] An onclick event will be implemented to allow the user to view the venues in the selected region.
- [ ] The booking form will pop up
