### ISSUE TITLE
USER STORY: Booking system

### ISSUE THREAD

**Issue by Quack842** [Quack842/p4-dndcampaign#8]
As a **Site User** I can **book a venue that I have selected** so that **a have a spot for my campaign**.

**Acceptance Criteria**
1. When the user makes a booking, they will have an option to select the _year_, _date_ and _time_ when they want to book, through a calendar model.
2. Veneus will show if they cater for people with disabilities
3. Only available spots will be shown, unavailable spots will be disabled.
4. After the user has selected the year, date and time, they will fill in a form. Form will need the following Information:
- > Name of Campaign (Must be unique)
- > Booking person's name
- > All the players that will be attending, names

**Task**
- [ ] Add coding to make it possible to make an appointment.
- [ ] Return available time slots
- [ ] A form will be created with the required information.
