### ISSUE TITLE
USER STORY: Create a Campaign

### ISSUE THREAD

**Issue by Quack842** [Quack842/p4-dndcampaign#9]
As a **Site User** I can **Create a campaign** so that **I can make a booking**. 

**Acceptance Criteria**
1. User can only create a campaign if they have an account.
2. User can Give their campaign a new name (The name must be unique)
3. The user can add a description if they want to.
4. The user have to select the total amount of players that will attend the venue, max of 8 players including DM
5. The user will have to give a name for each player that is attending. These names does not have to be unique

**Task**
- [ ] Criteria for logged in met, they will be able create a campaign
- [ ] Logged in criteria not met, they will be taken to the Login/Register page
- [ ] Username criteria not met, error will show that name is taken.
- [ ] Summernote will be added for description
- [ ] Total player scroll bar will be added
- [ ] Input fields will show depending on amount of players attending
